version: '3'
services:
  wiremock:
    image: rodolpheche/wiremock:2.30.1
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
  app: 
    image: rkawakami82/api-transferencia:latest
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:h2:mem:base_mem
      - DATABASE_DRIVER=org.h2.Driver
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=123
      - DATABASE_CONSOLE_ENABLED=true
      - DATABASE_PATH=/h2-console
      - SWAGGER_ATIVAR=true
      - CLIENTE_API=http://localhost:9090/clientes/
      - CONTA_API=http://localhost:9090/contas/
      - NOTIFICACAO_API=http://localhost:9090/notificacoes